package com.lefu.lefubao.model.entity;

import java.util.Date;

public class CustomerQualificationInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_qualification_info.ID
     *
     * @mbggenerated Thu Apr 13 14:49:09 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_qualification_info.OPTIMISTIC
     *
     * @mbggenerated Thu Apr 13 14:49:09 CST 2017
     */
    private Integer optimistic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_qualification_info.CUSTOMER_NO
     *
     * @mbggenerated Thu Apr 13 14:49:09 CST 2017
     */
    private String customerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_qualification_info.FILE_TYPE
     *
     * @mbggenerated Thu Apr 13 14:49:09 CST 2017
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_qualification_info.FILE_PATH
     *
     * @mbggenerated Thu Apr 13 14:49:09 CST 2017
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_qualification_info.FILE_INDEX
     *
     * @mbggenerated Thu Apr 13 14:49:09 CST 2017
     */
    private Integer fileIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_qualification_info.REMARK
     *
     * @mbggenerated Thu Apr 13 14:49:09 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_qualification_info.CREATE_TIME
     *
     * @mbggenerated Thu Apr 13 14:49:09 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_qualification_info.ID
     *
     * @return the value of customer_qualification_info.ID
     *
     * @mbggenerated Thu Apr 13 14:49:09 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_qualification_info.ID
     *
     * @param id the value for customer_qualification_info.ID
     *
     * @mbggenerated Thu Apr 13 14:49:09 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_qualification_info.OPTIMISTIC
     *
     * @return the value of customer_qualification_info.OPTIMISTIC
     *
     * @mbggenerated Thu Apr 13 14:49:09 CST 2017
     */
    public Integer getOptimistic() {
        return optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_qualification_info.OPTIMISTIC
     *
     * @param optimistic the value for customer_qualification_info.OPTIMISTIC
     *
     * @mbggenerated Thu Apr 13 14:49:09 CST 2017
     */
    public void setOptimistic(Integer optimistic) {
        this.optimistic = optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_qualification_info.CUSTOMER_NO
     *
     * @return the value of customer_qualification_info.CUSTOMER_NO
     *
     * @mbggenerated Thu Apr 13 14:49:09 CST 2017
     */
    public String getCustomerNo() {
        return customerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_qualification_info.CUSTOMER_NO
     *
     * @param customerNo the value for customer_qualification_info.CUSTOMER_NO
     *
     * @mbggenerated Thu Apr 13 14:49:09 CST 2017
     */
    public void setCustomerNo(String customerNo) {
        this.customerNo = customerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_qualification_info.FILE_TYPE
     *
     * @return the value of customer_qualification_info.FILE_TYPE
     *
     * @mbggenerated Thu Apr 13 14:49:09 CST 2017
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_qualification_info.FILE_TYPE
     *
     * @param fileType the value for customer_qualification_info.FILE_TYPE
     *
     * @mbggenerated Thu Apr 13 14:49:09 CST 2017
     */
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_qualification_info.FILE_PATH
     *
     * @return the value of customer_qualification_info.FILE_PATH
     *
     * @mbggenerated Thu Apr 13 14:49:09 CST 2017
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_qualification_info.FILE_PATH
     *
     * @param filePath the value for customer_qualification_info.FILE_PATH
     *
     * @mbggenerated Thu Apr 13 14:49:09 CST 2017
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_qualification_info.FILE_INDEX
     *
     * @return the value of customer_qualification_info.FILE_INDEX
     *
     * @mbggenerated Thu Apr 13 14:49:09 CST 2017
     */
    public Integer getFileIndex() {
        return fileIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_qualification_info.FILE_INDEX
     *
     * @param fileIndex the value for customer_qualification_info.FILE_INDEX
     *
     * @mbggenerated Thu Apr 13 14:49:09 CST 2017
     */
    public void setFileIndex(Integer fileIndex) {
        this.fileIndex = fileIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_qualification_info.REMARK
     *
     * @return the value of customer_qualification_info.REMARK
     *
     * @mbggenerated Thu Apr 13 14:49:09 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_qualification_info.REMARK
     *
     * @param remark the value for customer_qualification_info.REMARK
     *
     * @mbggenerated Thu Apr 13 14:49:09 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_qualification_info.CREATE_TIME
     *
     * @return the value of customer_qualification_info.CREATE_TIME
     *
     * @mbggenerated Thu Apr 13 14:49:09 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_qualification_info.CREATE_TIME
     *
     * @param createTime the value for customer_qualification_info.CREATE_TIME
     *
     * @mbggenerated Thu Apr 13 14:49:09 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}