package com.lefu.lefubao.model.entity;

import java.util.Date;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.ID
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.OPTIMISTIC
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    private Integer optimistic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.AGENT_NO
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    private String agentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.FULL_NAME
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    private String fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.SHORT_NAME
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.CUSTOMER_NO
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    private String customerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.MCC
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    private String mcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.CREATE_DATE
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.ORGANIZATION_CODE
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    private String organizationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.PHONE_NO
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    private String phoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.RECEIVE_ADDRESS
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    private String receiveAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.LINKMAN
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.STATUS
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.CUST_TYPE
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    private String custType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.BUSSNESS_TYPE
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    private String bussnessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.BUREGISTER_NO
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    private String buregisterNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.PROD_TYPE
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    private String prodType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.EXT_ATT
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    private String extAtt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.IS_AUTH_SETTLE
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    private String isAuthSettle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.AUTH_SETTLE_PERSON
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    private String authSettlePerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.AUTH_SETTLE_IDENTITYNO
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    private String authSettleIdentityno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.RECOMMENDER_NO
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    private String recommenderNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.ID
     *
     * @return the value of customer.ID
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.ID
     *
     * @param id the value for customer.ID
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.OPTIMISTIC
     *
     * @return the value of customer.OPTIMISTIC
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public Integer getOptimistic() {
        return optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.OPTIMISTIC
     *
     * @param optimistic the value for customer.OPTIMISTIC
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public void setOptimistic(Integer optimistic) {
        this.optimistic = optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.AGENT_NO
     *
     * @return the value of customer.AGENT_NO
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public String getAgentNo() {
        return agentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.AGENT_NO
     *
     * @param agentNo the value for customer.AGENT_NO
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public void setAgentNo(String agentNo) {
        this.agentNo = agentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.FULL_NAME
     *
     * @return the value of customer.FULL_NAME
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.FULL_NAME
     *
     * @param fullName the value for customer.FULL_NAME
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.SHORT_NAME
     *
     * @return the value of customer.SHORT_NAME
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.SHORT_NAME
     *
     * @param shortName the value for customer.SHORT_NAME
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.CUSTOMER_NO
     *
     * @return the value of customer.CUSTOMER_NO
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public String getCustomerNo() {
        return customerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.CUSTOMER_NO
     *
     * @param customerNo the value for customer.CUSTOMER_NO
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public void setCustomerNo(String customerNo) {
        this.customerNo = customerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.MCC
     *
     * @return the value of customer.MCC
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public String getMcc() {
        return mcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.MCC
     *
     * @param mcc the value for customer.MCC
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public void setMcc(String mcc) {
        this.mcc = mcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.CREATE_DATE
     *
     * @return the value of customer.CREATE_DATE
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.CREATE_DATE
     *
     * @param createDate the value for customer.CREATE_DATE
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.ORGANIZATION_CODE
     *
     * @return the value of customer.ORGANIZATION_CODE
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public String getOrganizationCode() {
        return organizationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.ORGANIZATION_CODE
     *
     * @param organizationCode the value for customer.ORGANIZATION_CODE
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public void setOrganizationCode(String organizationCode) {
        this.organizationCode = organizationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.PHONE_NO
     *
     * @return the value of customer.PHONE_NO
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.PHONE_NO
     *
     * @param phoneNo the value for customer.PHONE_NO
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.RECEIVE_ADDRESS
     *
     * @return the value of customer.RECEIVE_ADDRESS
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public String getReceiveAddress() {
        return receiveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.RECEIVE_ADDRESS
     *
     * @param receiveAddress the value for customer.RECEIVE_ADDRESS
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public void setReceiveAddress(String receiveAddress) {
        this.receiveAddress = receiveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.LINKMAN
     *
     * @return the value of customer.LINKMAN
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.LINKMAN
     *
     * @param linkman the value for customer.LINKMAN
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.STATUS
     *
     * @return the value of customer.STATUS
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.STATUS
     *
     * @param status the value for customer.STATUS
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.CUST_TYPE
     *
     * @return the value of customer.CUST_TYPE
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public String getCustType() {
        return custType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.CUST_TYPE
     *
     * @param custType the value for customer.CUST_TYPE
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public void setCustType(String custType) {
        this.custType = custType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.BUSSNESS_TYPE
     *
     * @return the value of customer.BUSSNESS_TYPE
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public String getBussnessType() {
        return bussnessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.BUSSNESS_TYPE
     *
     * @param bussnessType the value for customer.BUSSNESS_TYPE
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public void setBussnessType(String bussnessType) {
        this.bussnessType = bussnessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.BUREGISTER_NO
     *
     * @return the value of customer.BUREGISTER_NO
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public String getBuregisterNo() {
        return buregisterNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.BUREGISTER_NO
     *
     * @param buregisterNo the value for customer.BUREGISTER_NO
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public void setBuregisterNo(String buregisterNo) {
        this.buregisterNo = buregisterNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.PROD_TYPE
     *
     * @return the value of customer.PROD_TYPE
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public String getProdType() {
        return prodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.PROD_TYPE
     *
     * @param prodType the value for customer.PROD_TYPE
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public void setProdType(String prodType) {
        this.prodType = prodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.EXT_ATT
     *
     * @return the value of customer.EXT_ATT
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public String getExtAtt() {
        return extAtt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.EXT_ATT
     *
     * @param extAtt the value for customer.EXT_ATT
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public void setExtAtt(String extAtt) {
        this.extAtt = extAtt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.IS_AUTH_SETTLE
     *
     * @return the value of customer.IS_AUTH_SETTLE
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public String getIsAuthSettle() {
        return isAuthSettle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.IS_AUTH_SETTLE
     *
     * @param isAuthSettle the value for customer.IS_AUTH_SETTLE
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public void setIsAuthSettle(String isAuthSettle) {
        this.isAuthSettle = isAuthSettle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.AUTH_SETTLE_PERSON
     *
     * @return the value of customer.AUTH_SETTLE_PERSON
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public String getAuthSettlePerson() {
        return authSettlePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.AUTH_SETTLE_PERSON
     *
     * @param authSettlePerson the value for customer.AUTH_SETTLE_PERSON
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public void setAuthSettlePerson(String authSettlePerson) {
        this.authSettlePerson = authSettlePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.AUTH_SETTLE_IDENTITYNO
     *
     * @return the value of customer.AUTH_SETTLE_IDENTITYNO
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public String getAuthSettleIdentityno() {
        return authSettleIdentityno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.AUTH_SETTLE_IDENTITYNO
     *
     * @param authSettleIdentityno the value for customer.AUTH_SETTLE_IDENTITYNO
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public void setAuthSettleIdentityno(String authSettleIdentityno) {
        this.authSettleIdentityno = authSettleIdentityno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.RECOMMENDER_NO
     *
     * @return the value of customer.RECOMMENDER_NO
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public String getRecommenderNo() {
        return recommenderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.RECOMMENDER_NO
     *
     * @param recommenderNo the value for customer.RECOMMENDER_NO
     *
     * @mbggenerated Thu Apr 13 14:50:28 CST 2017
     */
    public void setRecommenderNo(String recommenderNo) {
        this.recommenderNo = recommenderNo;
    }
}