package com.lefu.lefubao.model.entity;

import java.util.Date;

public class CustomerSettleCard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_settle_card.ID
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_settle_card.OPTIMISTIC
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    private Integer optimistic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_settle_card.OWNER_ID
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    private String ownerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_settle_card.STATUS
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_settle_card.SETTLE_ACCOUNT_TYPE
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    private String settleAccountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_settle_card.BANK_ACCOUNT_NAME
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    private String bankAccountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_settle_card.BANK_ACCOUNT_NO
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    private String bankAccountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_settle_card.BANK_CODE
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    private String bankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_settle_card.BANK_NAME
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_settle_card.ALLIED_BANK_CODE
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    private String alliedBankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_settle_card.SABK_CODE
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    private String sabkCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_settle_card.OWN_BANK_CODE
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    private String ownBankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_settle_card.PROVINCE
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_settle_card.CITY
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_settle_card.PRIORITY
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    private String priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_settle_card.CARD_INDEX
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    private String cardIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_settle_card.CREATE_DATE
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_settle_card.ID
     *
     * @return the value of customer_settle_card.ID
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_settle_card.ID
     *
     * @param id the value for customer_settle_card.ID
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_settle_card.OPTIMISTIC
     *
     * @return the value of customer_settle_card.OPTIMISTIC
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public Integer getOptimistic() {
        return optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_settle_card.OPTIMISTIC
     *
     * @param optimistic the value for customer_settle_card.OPTIMISTIC
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public void setOptimistic(Integer optimistic) {
        this.optimistic = optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_settle_card.OWNER_ID
     *
     * @return the value of customer_settle_card.OWNER_ID
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_settle_card.OWNER_ID
     *
     * @param ownerId the value for customer_settle_card.OWNER_ID
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_settle_card.STATUS
     *
     * @return the value of customer_settle_card.STATUS
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_settle_card.STATUS
     *
     * @param status the value for customer_settle_card.STATUS
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_settle_card.SETTLE_ACCOUNT_TYPE
     *
     * @return the value of customer_settle_card.SETTLE_ACCOUNT_TYPE
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public String getSettleAccountType() {
        return settleAccountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_settle_card.SETTLE_ACCOUNT_TYPE
     *
     * @param settleAccountType the value for customer_settle_card.SETTLE_ACCOUNT_TYPE
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public void setSettleAccountType(String settleAccountType) {
        this.settleAccountType = settleAccountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_settle_card.BANK_ACCOUNT_NAME
     *
     * @return the value of customer_settle_card.BANK_ACCOUNT_NAME
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public String getBankAccountName() {
        return bankAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_settle_card.BANK_ACCOUNT_NAME
     *
     * @param bankAccountName the value for customer_settle_card.BANK_ACCOUNT_NAME
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public void setBankAccountName(String bankAccountName) {
        this.bankAccountName = bankAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_settle_card.BANK_ACCOUNT_NO
     *
     * @return the value of customer_settle_card.BANK_ACCOUNT_NO
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public String getBankAccountNo() {
        return bankAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_settle_card.BANK_ACCOUNT_NO
     *
     * @param bankAccountNo the value for customer_settle_card.BANK_ACCOUNT_NO
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public void setBankAccountNo(String bankAccountNo) {
        this.bankAccountNo = bankAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_settle_card.BANK_CODE
     *
     * @return the value of customer_settle_card.BANK_CODE
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_settle_card.BANK_CODE
     *
     * @param bankCode the value for customer_settle_card.BANK_CODE
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_settle_card.BANK_NAME
     *
     * @return the value of customer_settle_card.BANK_NAME
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_settle_card.BANK_NAME
     *
     * @param bankName the value for customer_settle_card.BANK_NAME
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_settle_card.ALLIED_BANK_CODE
     *
     * @return the value of customer_settle_card.ALLIED_BANK_CODE
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public String getAlliedBankCode() {
        return alliedBankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_settle_card.ALLIED_BANK_CODE
     *
     * @param alliedBankCode the value for customer_settle_card.ALLIED_BANK_CODE
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public void setAlliedBankCode(String alliedBankCode) {
        this.alliedBankCode = alliedBankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_settle_card.SABK_CODE
     *
     * @return the value of customer_settle_card.SABK_CODE
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public String getSabkCode() {
        return sabkCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_settle_card.SABK_CODE
     *
     * @param sabkCode the value for customer_settle_card.SABK_CODE
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public void setSabkCode(String sabkCode) {
        this.sabkCode = sabkCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_settle_card.OWN_BANK_CODE
     *
     * @return the value of customer_settle_card.OWN_BANK_CODE
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public String getOwnBankCode() {
        return ownBankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_settle_card.OWN_BANK_CODE
     *
     * @param ownBankCode the value for customer_settle_card.OWN_BANK_CODE
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public void setOwnBankCode(String ownBankCode) {
        this.ownBankCode = ownBankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_settle_card.PROVINCE
     *
     * @return the value of customer_settle_card.PROVINCE
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_settle_card.PROVINCE
     *
     * @param province the value for customer_settle_card.PROVINCE
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_settle_card.CITY
     *
     * @return the value of customer_settle_card.CITY
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_settle_card.CITY
     *
     * @param city the value for customer_settle_card.CITY
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_settle_card.PRIORITY
     *
     * @return the value of customer_settle_card.PRIORITY
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public String getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_settle_card.PRIORITY
     *
     * @param priority the value for customer_settle_card.PRIORITY
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public void setPriority(String priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_settle_card.CARD_INDEX
     *
     * @return the value of customer_settle_card.CARD_INDEX
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public String getCardIndex() {
        return cardIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_settle_card.CARD_INDEX
     *
     * @param cardIndex the value for customer_settle_card.CARD_INDEX
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public void setCardIndex(String cardIndex) {
        this.cardIndex = cardIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_settle_card.CREATE_DATE
     *
     * @return the value of customer_settle_card.CREATE_DATE
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_settle_card.CREATE_DATE
     *
     * @param createDate the value for customer_settle_card.CREATE_DATE
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}