package com.lefu.lefubao.core.dao;

import com.lefu.lefubao.model.entity.CustomerSettleCard;

public interface CustomerSettleCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_settle_card
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_settle_card
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    int insert(CustomerSettleCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_settle_card
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    int insertSelective(CustomerSettleCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_settle_card
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    CustomerSettleCard selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_settle_card
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    int updateByPrimaryKeySelective(CustomerSettleCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_settle_card
     *
     * @mbggenerated Thu Apr 13 14:47:28 CST 2017
     */
    int updateByPrimaryKey(CustomerSettleCard record);
}